### ISSUE TITLE
Some yokel broked the site

### ISSUE THREAD

**Issue by JakePartusch** [DSchau/presentations#2]
Reproduction Steps:
1. Visit [this site](https://dschau-presentations.netlify.com/)
2. See that it doesn't work 😋

**Comment by DSchau** [comment]
They’re all hosted on a sub-path of the main domain—but I should probably make it so there’s a listing!

**Comment by JakePartusch** [comment]
Just giving you a hard time 👋

Thanks though, paths like this work 🙌:
https://dschau-presentations.netlify.com/beyond-static
